CREATE DATABASE Shopping_Behaviour_DB;
USE Shopping_Behaviour_DB;
SHOW TABLES;

---Q1. Total revenue generated by male vs female customers.
SELECT 
    Gender, 
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS revenue
FROM Customer1
GROUP BY Gender;

---Q2. Customers who used discounts and spent above average.
SELECT 
    Customer_ID,
    `Purchase_Amount_(USD)`
FROM Customer1
WHERE Discount_Applied = 'Yes'
AND `Purchase_Amount_(USD)` >= (
    SELECT AVG(`Purchase_Amount_(USD)`) FROM Customer1
);

---Q3. Top 5 products with highest average rating.
SELECT 
    Item_Purchased,
    ROUND(AVG(Review_Rating), 2) AS avg_rating
FROM Customer1
GROUP BY Item_Purchased
ORDER BY avg_rating DESC
LIMIT 5;

---Q4. Average purchase amount by shipping type.
SELECT 
    Shipping_Type,
    ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_purchase
FROM Customer1
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type;

---Q5. Subscriber vs non-subscriber comparison.
SELECT 
    Subscription_Status,
    COUNT(Customer_ID) AS total_customers,
    ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_spend,
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS total_revenue
FROM Customer1
GROUP BY Subscription_Status
ORDER BY total_revenue DESC;

---Q6. Top 5 products with highest discount usage.
SELECT 
    Item_Purchased,
    ROUND(
        100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM Customer1
GROUP BY Item_Purchased
ORDER BY discount_rate DESC
LIMIT 5;

---Q7. Customer segmentation (New / Returning / Loyal).
WITH customer_type AS (
    SELECT 
        Customer_ID,
        CASE
            WHEN Previous_Purchases = 1 THEN 'New'
            WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM Customer1
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

---Q8. Top 3 most purchased products per category.
WITH item_counts AS (
    SELECT 
        Category,
        Item_Purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY Category 
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM Customer1
    GROUP BY Category, Item_Purchased
)
SELECT 
    Category,
    Item_Purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

---Q9. Subscription likelihood among repeat buyers.
SELECT 
    Subscription_Status,
    COUNT(Customer_ID) AS repeat_buyers
FROM Customer1
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

---Q10. Revenue contribution by age group.
SELECT 
    Age_Group,
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS total_revenue
FROM Customer1
GROUP BY Age_Group
ORDER BY total_revenue DESC;

---Q11. Revenue by shipping type.
SELECT 
    Shipping_Type,
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS total_revenue
FROM Customer1
GROUP BY Shipping_Type
ORDER BY total_revenue DESC;

---Q12. Highest spending season.
SELECT 
    Season,
    ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_spend
FROM Customer1
GROUP BY Season
ORDER BY avg_spend DESC;

---Q13. High revenue but low-rated categories.
SELECT 
    Category,
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS total_revenue,
    ROUND(AVG(Review_Rating), 2) AS avg_rating
FROM Customer1
GROUP BY Category
HAVING AVG(Review_Rating) < 3
ORDER BY total_revenue DESC;

---Q14. Revenue percentage from subscribers.
SELECT 
    Subscription_Status,
    ROUND(
        100.0 * SUM(`Purchase_Amount_(USD)`) /
        (SELECT SUM(`Purchase_Amount_(USD)`) FROM Customer1),
        2
    ) AS revenue_percentage
FROM Customer1
GROUP BY Subscription_Status;

---Q15. Rank customers by spending within each location.
WITH customer_spend AS (
    SELECT 
        Location,
        Customer_ID,
        SUM(`Purchase_Amount_(USD)`) AS total_spent
    FROM Customer1
    GROUP BY Location, Customer_ID
)
SELECT 
    Location,
    Customer_ID,
    total_spent,
    RANK() OVER (
        PARTITION BY Location 
        ORDER BY total_spent DESC
    ) AS spend_rank
FROM customer_spend;
